#build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

COPY OurCity.MigrationsRunner/*.csproj .
RUN dotnet restore

COPY . .

WORKDIR /app/OurCity.MigrationsRunner

RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

#runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

#non-root
USER app

ENTRYPOINT ["dotnet", "OurCity.MigrationsRunner.dll"]